server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  # data source
  datasource:
    url: jdbc:mysql://localhost:3306/db-blog?createDatabaseIfNotExist=true
    username: root
    password: 06121994
    #JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  #security
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://YOUR_DOMAIN/
#auth0:
#  audience: https://websale/api




